#pragma once

#include <RED4ext/Api/Sdk.hpp>
#include <RED4ext/Api/Version.hpp>

#define MINIMUM_API_VERSION RED4EXT_API_VERSION_0
#define LATEST_API_VERSION RED4EXT_API_VERSION_LATEST

#define MINIMUM_SDK_VERSION RED4EXT_SDK_0_1_0
#define LATEST_SDK_VERSION RED4EXT_SDK_LATEST
