function(red4ext_configure_resource_rc TARGET DESCRIPTION)
  get_target_property(RED4EXT_RESOURCE_PRODUCT_NAME "${TARGET}" OUTPUT_NAME)
  if ("${RED4EXT_RESOURCE_PRODUCT_NAME}" STREQUAL "RED4EXT_RESOURCE_PRODUCT_NAME-NOTFOUND")
    set(RED4EXT_RESOURCE_PRODUCT_NAME "${TARGET}")
  endif()

  set(RED4EXT_RESOURCE_FILE_DESCRIPTION "${DESCRIPTION}")
  set(RED4EXT_RESOURCE_INTERNAL_NAME "${RED4EXT_RESOURCE_PRODUCT_NAME}${CMAKE_SHARED_LIBRARY_SUFFIX}")
  set(RED4EXT_RESOURCE_ORIGINAL_NAME "${RED4EXT_RESOURCE_PRODUCT_NAME}${CMAKE_SHARED_LIBRARY_SUFFIX}")

  set(OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/Resource.rc")

  configure_file(
    "${RED4EXT_CMAKE_TEMPLATES_DIR}/Resource.rc.in"
    "${OUTPUT_FILE}"
    @ONLY
  )

  set(RED4EXT_RC_FILE "${OUTPUT_FILE}" PARENT_SCOPE)
endfunction()
