option(SIMDJSON_BASH "" OFF)

add_subdirectory(deps/simdjson)
set_target_properties(simdjson PROPERTIES FOLDER "Dependencies")

mark_as_advanced(
  SIMDJSON_AVX512_ALLOWED
  SIMDJSON_BASH
  SIMDJSON_BUILD_STATIC_LIB
  SIMDJSON_BUILTIN_IMPLEMENTATION
  SIMDJSON_CHECK_EOF
  SIMDJSON_CXX_STANDARD
  SIMDJSON_DEVELOPMENT_CHECKS
  SIMDJSON_DISABLE_DEPRECATED_API
  SIMDJSON_ENABLE_THREADS
  SIMDJSON_EXCEPTIONS
  SIMDJSON_EXCLUDE_IMPLEMENTATION
  SIMDJSON_GLIBCXX_ASSERTIONS
  SIMDJSON_IMPLEMENTATION
  SIMDJSON_LIB_SOVERSION
  SIMDJSON_LIB_VERSION
  SIMDJSON_SANITIZE
  SIMDJSON_SANITIZE_MEMORY
  SIMDJSON_SANITIZE_UNDEFINED
  SIMDJSON_SKIPUTF8VALIDATION
  SIMDJSON_STRUCTURAL_INDEXER_STEP
  SIMDJSON_VERBOSE_LOGGING
  SIMDJSON_VISUAL_STUDIO_BUILD_WITH_DEBUG_INFO_FOR_PROFILING
)
